/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventorymanagementsystem;
 
/**
 *
 * @author Zentox
 */
public class Billing extends javax.swing.JFrame {
    javax.swing.table.DefaultTableModel model;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Billing.class.getName());

     private javax.swing.JPopupMenu searchPopup;
private javax.swing.JList<String> suggestionList;
private java.util.List<String> itemCodesList = new java.util.ArrayList<>();
 
    public Billing() {
        initComponents();
     
                model = (javax.swing.table.DefaultTableModel) tblbill.getModel();
    
    searchPopup = new javax.swing.JPopupMenu();
    suggestionList = new javax.swing.JList<>();
    searchPopup.add(new javax.swing.JScrollPane(suggestionList));
    searchPopup.setFocusable(false); 
    
    suggestionList.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int index = suggestionList.getSelectedIndex();
            if (index != -1) {
                String selectedCode = itemCodesList.get(index);
                txtsearch.setText(selectedCode);
                searchPopup.setVisible(false);
                
                txtqty.requestFocus();
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbill = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        lblGrandTotal = new javax.swing.JLabel();
        Reouv = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtsearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAddToCart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 153));

        tblbill.setBackground(new java.awt.Color(255, 255, 0));
        tblbill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Product Name", "Unit Price", "Quantity", "Total"
            }
        ));
        tblbill.setSelectionBackground(new java.awt.Color(51, 0, 204));
        tblbill.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblbill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbillMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbill);

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));

        btnClear.setBackground(new java.awt.Color(255, 204, 0));
        btnClear.setText("Clear Cart");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnGenerate.setBackground(new java.awt.Color(51, 204, 0));
        btnGenerate.setText("Generate Bill");
        btnGenerate.addActionListener(this::btnGenerateActionPerformed);

        lblGrandTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblGrandTotal.setForeground(new java.awt.Color(0, 204, 0));
        lblGrandTotal.setText("Grand Total: Rs. 0.00");

        Reouv.setBackground(new java.awt.Color(255, 153, 0));
        Reouv.setText("Remove Item");
        Reouv.addActionListener(this::ReouvActionPerformed);

        update.setBackground(new java.awt.Color(153, 255, 51));
        update.setText("Update");
        update.addActionListener(this::updateActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGenerate)
                .addGap(30, 30, 30)
                .addComponent(update)
                .addGap(29, 29, 29)
                .addComponent(Reouv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear)
                    .addComponent(btnGenerate)
                    .addComponent(Reouv)
                    .addComponent(update))
                .addGap(7, 7, 7))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        txtsearch.addActionListener(this::txtsearchActionPerformed);
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("HARDWARE BILLING SYSTEM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item ID / Barcode/Item naeme:");

        txtqty.addActionListener(this::txtqtyActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantity:");

        btnAddToCart.setBackground(new java.awt.Color(51, 255, 153));
        btnAddToCart.setText("Add to Cart");
        btnAddToCart.addActionListener(this::btnAddToCartActionPerformed);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slip.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(0, 255, 51));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Deneth Software's");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnAddToCart)))
                .addGap(7, 7, 7)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddToCart)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
 String searchData = txtsearch.getText().trim();
    String qtyText = txtqty.getText().trim();
    
  
    if (searchData.isEmpty() || qtyText.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Item and Quantity!");
        return;
    }
    
    try {
        int qty = Integer.parseInt(qtyText);
        
        if (qty <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be greater than 0!");
            return;
        }
        
        java.sql.Connection con = com.mycompany.inventorymanagementsystem.db.mycon();
        
      
        String sql = "SELECT item_code, item_name, selling_price, qty FROM items WHERE item_code=? OR barcode=?";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, searchData);
        pst.setString(2, searchData);
        
        java.sql.ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            String code = rs.getString("item_code");
            String name = rs.getString("item_name");
            double price = rs.getDouble("selling_price");
            int availableQty = rs.getInt("qty");
            
   
            if (qty > availableQty) {
                javax.swing.JOptionPane.showMessageDialog(this, "Sorry! Only " + availableQty + " items available in Stock.");
                return;
            }
            
            double total = price * qty;
            javax.swing.table.DefaultTableModel dt = (javax.swing.table.DefaultTableModel) tblbill.getModel();
            
            boolean isExist = false;
            int existingRow = -1;
            
           
            for (int i = 0; i < dt.getRowCount(); i++) {
                if (dt.getValueAt(i, 0) != null) { 
                    if (dt.getValueAt(i, 0).toString().equals(code)) {
                        isExist = true;
                        existingRow = i;
                        break;
                    }
                }
            }
            
            if (isExist) {

                int oldQty = Integer.parseInt(dt.getValueAt(existingRow, 3).toString());
                int newQty = oldQty + qty;
                
                
                if (newQty > availableQty) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Cannot add more! Stock limit exceeded.");
                    return;
                }
                
                double newTotal = price * newQty;
                dt.setValueAt(newQty, existingRow, 3); 
                dt.setValueAt(newTotal, existingRow, 4); 
            } else {
              
                java.util.Vector v = new java.util.Vector();
                v.add(code);      
                v.add(name);      
                v.add(price);     
                v.add(qty);       
                v.add(total);     
                dt.addRow(v);
            }
            
        
            String updateSql = "UPDATE items SET qty = qty - ? WHERE item_code = ?";
            java.sql.PreparedStatement updatePst = con.prepareStatement(updateSql);
            updatePst.setInt(1, qty); 
            updatePst.setString(2, code);
            updatePst.executeUpdate(); 
            
           
            updateGrandTotal();
            
            
            txtsearch.setText("");
            txtqty.setText("");
            txtsearch.requestFocus(); 
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Item Error! Please search again.");
        }
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number for Quantity!");
    } catch (Exception e) {
        System.out.println("Add to Cart Error: " + e.getMessage());
    }
// TODO add your handling code here:
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
     model.setRowCount(0);
txtsearch.setText("");
txtqty.setText("");
lblGrandTotal.setText("Grand Total: Rs. 0.00");      
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
 javax.swing.table.DefaultTableModel dt = (javax.swing.table.DefaultTableModel) tblbill.getModel();
    int rowCount = dt.getRowCount();
    double grandTotal = 0;
    
    for (int i = 0; i < rowCount; i++) {
        if (dt.getValueAt(i, 4) != null) {
            grandTotal += Double.parseDouble(dt.getValueAt(i, 4).toString());
        }
    }
    
    
    lblGrandTotal.setText("Grand Total: Rs. " + String.format("%.2f", grandTotal));    // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        String searchData = txtsearch.getText().trim();
    
 
    if (searchData.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Item ID or Barcode!");
        return;
    }
    
    try {
      
        java.sql.Connection con = com.mycompany.inventorymanagementsystem.db.mycon();
        
      
        String sql = "SELECT item_code, item_name, selling_price FROM items WHERE item_code=? OR barcode=?";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, searchData);
        pst.setString(2, searchData);
        
        java.sql.ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
           
            txtqty.requestFocus();
            
        } else {
          
            javax.swing.JOptionPane.showMessageDialog(this, "Item Not Found in Database!");
            txtsearch.setText("");
            txtsearch.requestFocus();
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Search Error: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtyActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
         String text = txtsearch.getText().trim();
    
  
    if (text.length() < 2) {
        searchPopup.setVisible(false);
        return;
    }
    
  
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER || 
        evt.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN || 
        evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP) {
        return;
    }
    
    try {
        java.sql.Connection con = com.mycompany.inventorymanagementsystem.db.mycon();
        
        
        String sql = "SELECT item_code, item_name, selling_price FROM items WHERE item_name LIKE ? OR barcode LIKE ? LIMIT 10";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, "%" + text + "%");
        pst.setString(2, "%" + text + "%");
        
        java.sql.ResultSet rs = pst.executeQuery();
        
        javax.swing.DefaultListModel<String> listModel = new javax.swing.DefaultListModel<>();
        itemCodesList.clear();
        
        boolean hasData = false;
        while (rs.next()) {
            hasData = true;
            String code = rs.getString("item_code");
            String name = rs.getString("item_name");
            double price = rs.getDouble("selling_price");
            
            
            listModel.addElement(name + "   |   Rs." + price);
            itemCodesList.add(code); }
        if (hasData) {
            suggestionList.setModel(listModel);
            
          
            suggestionList.setFixedCellHeight(25);
            searchPopup.setPopupSize(txtsearch.getWidth(), 150); 
            
           
            searchPopup.show(txtsearch, 0, txtsearch.getHeight());
            txtsearch.requestFocus(); // Focus එක සර්ච් බොක්ස් එකේම තියාගන්නවා
        } else {
            searchPopup.setVisible(false);
        }
        
    } catch (Exception e) {
        System.out.println("Live Search Error: " + e.getMessage());
    }    // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchKeyReleased

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
int selectedRow = tblbill.getSelectedRow();
    
   
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an item from the table to update!");
        return;
    }
    
   
    String qtyText = txtqty.getText().trim();
    if (qtyText.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid Quantity!");
        return;
    }
    
    try {
        int newQty = Integer.parseInt(qtyText);
        if (newQty <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be greater than 0!");
            return;
        }
        
        
        double price = Double.parseDouble(tblbill.getValueAt(selectedRow, 2).toString());
        
       
        double newTotal = price * newQty;
        
      
        tblbill.setValueAt(newQty, selectedRow, 3); 
        tblbill.setValueAt(newTotal, selectedRow, 4); 
        
       
        updateGrandTotal();
        
     
        txtsearch.setText("");
        txtqty.setText("");
        tblbill.clearSelection(); 
        txtsearch.requestFocus();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Item quantity updated successfully!");
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number for Quantity!");
    } catch (Exception e) {
        System.out.println("Update Error: " + e.getMessage());
    }
    }//GEN-LAST:event_updateActionPerformed

    private void ReouvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReouvActionPerformed
       int selectedRow = tblbill.getSelectedRow();
    
  
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an item from the table to remove!");
        return;
    }
    
  
    javax.swing.table.DefaultTableModel dt = (javax.swing.table.DefaultTableModel) tblbill.getModel();
    dt.removeRow(selectedRow);
    

    updateGrandTotal();
    
   
    txtsearch.setText("");
    txtqty.setText("");
    tblbill.clearSelection();
    txtsearch.requestFocus();
    
    javax.swing.JOptionPane.showMessageDialog(this, "Item removed from cart!");        // TODO add your handling code here:
    }//GEN-LAST:event_ReouvActionPerformed

    private void tblbillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbillMouseClicked
              int row = tblbill.getSelectedRow();
if(row != -1){
    txtsearch.setText(tblbill.getValueAt(row, 0).toString());
    txtqty.setText(tblbill.getValueAt(row, 3).toString());
}                     // TODO add your handling code here:
                    // TODO add your handling code here:
     // TODO add your handling code here:
    }//GEN-LAST:event_tblbillMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Billing().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reouv;
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JTable tblbill;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private void updateGrandTotal() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
