
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.inventorymanagementsystem;

public class ItemManagement extends javax.swing.JPanel {
/**
 *
 * @author Zentox

 */

 private java.sql.Statement statement;
 private java.sql.ResultSet resultSet;
 private java.sql.Connection connection;
    /**
     * Creates new form ItemManagement
     */
    public ItemManagement() {
       initComponents();
       
        table_load(); //
        auto_code();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        txtcode = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        costprice = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcostprice = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbcategory = new javax.swing.JComboBox<>();
        btnadd = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(51, 255, 255));
        setPreferredSize(new java.awt.Dimension(801, 463));

        tblItems.setBackground(new java.awt.Color(255, 255, 0));
        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Item code", "Item Name", "Category", "Quantity", "Cost price", "selling price", "Barcode"
            }
        ));
        tblItems.setSelectionBackground(new java.awt.Color(0, 51, 204));
        tblItems.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItems);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Item Mangement");

        txtqty.addActionListener(this::txtqtyActionPerformed);

        txtname.addActionListener(this::txtnameActionPerformed);

        jLabel4.setText("ItemCode");

        jLabel5.setText("Category");

        jLabel6.setText("ItemName");

        txtcostprice.setText("CostPrice");

        jLabel9.setText("SellingPrice");

        jLabel8.setText("Quantity");

        cmbcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tools & Equipment", "Fasteners & Hardware ", "Electrical & Lighting", "Plumbing & Civil Materials", "Paints & Adhesives" }));
        cmbcategory.addActionListener(this::cmbcategoryActionPerformed);

        btnadd.setBackground(new java.awt.Color(51, 255, 0));
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-to-cart.png"))); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(this::btnaddActionPerformed);

        jButton10.setBackground(new java.awt.Color(255, 0, 0));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jButton10.setText("Delete");
        jButton10.addActionListener(this::jButton10ActionPerformed);

        jButton11.setBackground(new java.awt.Color(255, 255, 0));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clean.png"))); // NOI18N
        jButton11.setText("Clear");
        jButton11.addActionListener(this::jButton11ActionPerformed);

        jButton12.setBackground(new java.awt.Color(255, 102, 0));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updated.png"))); // NOI18N
        jButton12.setText("Update");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(this::jButton12ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcostprice)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(costprice, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtprice)
                                .addGap(82, 82, 82))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton12)
                        .addGap(35, 35, 35)
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(costprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcostprice))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(42, 42, 42)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton10)
                    .addComponent(jButton12)
                    .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
     
    
    
   
   auto_code(); 
    
    String itemCode = txtcode.getText(); 
    String itemName = txtname.getText();
    String category = cmbcategory.getSelectedItem().toString(); 
    String qty = txtqty.getText();
    String costPrice = costprice.getText(); 
    String sellingPrice = txtprice.getText(); 

    java.sql.Connection con = com.mycompany.inventorymanagementsystem.db.mycon();
    
    try {
        
        String sql = "INSERT INTO items (item_code, item_name, category, qty, price, selling_price, barcode) VALUES (?, ?, ?, ?, ?, ?, ?)";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        
        pst.setString(1, itemCode); 
        pst.setString(2, itemName);
        pst.setString(3, category);
        
        int finalQty = qty.isEmpty() ? 0 : Integer.parseInt(qty);
        double finalCost = costPrice.isEmpty() ? 0.0 : Double.parseDouble(costPrice);
        double finalSell = sellingPrice.isEmpty() ? 0.0 : Double.parseDouble(sellingPrice); 
        
        pst.setInt(4, finalQty);
        pst.setDouble(5, finalCost); 
        pst.setDouble(6, finalSell); 
        
      
        pst.setString(7, barcode()); 
        
        pst.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Item Added Successfully!");
        
        table_load();
        
       
        txtname.setText("");
        txtqty.setText("");
        costprice.setText("");
        txtprice.setText("");
        cmbcategory.setSelectedIndex(0);
        
        auto_code();
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage()); 
    
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtyActionPerformed

    private void cmbcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcategoryActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
                                                
        String id = txtcode.getText(); 
        
        try {
            java.sql.Connection con = com.mycompany.inventorymanagementsystem.db.mycon();
            java.sql.Statement s = con.createStatement();
            
         
            s.executeUpdate("DELETE FROM items WHERE item_code = '"+id+"'");
            
          
            javax.swing.JOptionPane.showMessageDialog(this, "Item Deleted Successfully!");
            table_load(); 
          
            txtcode.setText("");
            txtname.setText("");
            txtqty.setText("");
            costprice.setText("");
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
                                       
      String code = txtcode.getText();
    String name = txtname.getText();
    String cat = cmbcategory.getSelectedItem().toString();
    String qty = txtqty.getText();
    String price = costprice.getText();
    String s_price = txtprice.getText(); 
    
    try {
        java.sql.Connection con = com.mycompany.inventorymanagementsystem.db.mycon();
        java.sql.Statement s = con.createStatement();
        
      
        s.executeUpdate("UPDATE items SET item_name='"+name+"', category='"+cat+"', qty='"+qty+"', price='"+price+"', selling_price='"+s_price+"' WHERE item_code='"+code+"' ");
        
        javax.swing.JOptionPane.showMessageDialog(this, "Item Updated Successfully!");
        table_load();
        
        
        txtname.setText("");
        txtqty.setText("");
        costprice.setText("");
        txtprice.setText("");
        cmbcategory.setSelectedIndex(0);
        auto_code();
        
    } catch (Exception e) {
        System.out.println(e.getMessage());
    }                               
   
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void tblItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemsMouseClicked
       try {
        int r = tblItems.getSelectedRow(); 
        
        String code = tblItems.getValueAt(r, 0).toString();
        String name = tblItems.getValueAt(r, 1).toString();
        String cat = tblItems.getValueAt(r, 2).toString();
        String qty = tblItems.getValueAt(r, 3).toString();
        String c_price = tblItems.getValueAt(r, 4).toString(); 
        String s_price = tblItems.getValueAt(r, 5).toString(); 
        
       
        txtcode.setText(code);      
        txtname.setText(name);  
        cmbcategory.setSelectedItem(cat); 
        txtqty.setText(qty);    
        costprice.setText(c_price); 
        txtprice.setText(s_price);   
        
    } catch (Exception e) {
         System.out.println(e.getMessage());
    }
            // TODO add your handling code here:
    }//GEN-LAST:event_tblItemsMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
   String id = txtcode.getText(); 
        
        if (id.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an Item from the table to delete.");
            return;
        }
        
        int dialogResult = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to delete this Item?", "Warning", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (dialogResult == javax.swing.JOptionPane.YES_OPTION) {
            try {
                java.sql.Connection con = com.mycompany.inventorymanagementsystem.db.mycon();
                
                String sql = "DELETE FROM items WHERE item_code = ?";
                java.sql.PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, id);
                
                int rowsDeleted = pst.executeUpdate();
                
                if (rowsDeleted > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Item Deleted Successfully!");
                    table_load(); 
                    
                    txtcode.setText("");
                    txtname.setText("");
                    txtqty.setText("");
                    costprice.setText("");
                    txtprice.setText("");
                    cmbcategory.setSelectedIndex(0);
                    auto_code(); 
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Item not found or already deleted.");
                }
                
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Delete Error: " + e.getMessage());
            }
        
        }                                                                     
                                             
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      txtname.setText("");
    txtqty.setText("");
    costprice.setText("");
    txtprice.setText(""); 
    cmbcategory.setSelectedIndex(0);
    auto_code(); 

 
    }//GEN-LAST:event_jButton11ActionPerformed

public void table_load() {
    try {
        javax.swing.table.DefaultTableModel dt = (javax.swing.table.DefaultTableModel) tblItems.getModel();
        dt.setRowCount(0);

        java.sql.Connection con = com.mycompany.inventorymanagementsystem.db.mycon();
        java.sql.Statement s = con.createStatement();
        
        java.sql.ResultSet rs = s.executeQuery("SELECT * FROM items");

        while (rs.next()) {
            java.util.Vector v = new java.util.Vector();
            
            v.add(rs.getString("item_code"));
            v.add(rs.getString("item_name"));
            v.add(rs.getString("category"));
            v.add(rs.getString("qty"));
            v.add(rs.getString("price"));
            v.add(rs.getString("selling_price"));
            v.add(rs.getString("barcode"));
            
            dt.addRow(v);
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Table Load Error: " + e.getMessage());
    }
}
    
    
    
   public void auto_code() {
    try {
        connection = com.mycompany.inventorymanagementsystem.db.mycon();
        
        String query = "SELECT item_code FROM items ORDER BY item_code DESC LIMIT 1";
        statement = connection.createStatement();
        resultSet = statement.executeQuery(query);
        
        if (resultSet.next()) {
            String lastCode = resultSet.getString("item_code"); 
            
      
            if (lastCode != null && lastCode.length() > 2) {
                
                String idString = lastCode.substring(2); 
                int id = Integer.parseInt(idString.trim()); 
                id++; 
                
                txtcode.setText("It" + id); 
            } else {
                txtcode.setText("It1001");
            }
        } else {
            txtcode.setText("It1001"); 
        }
        
    } catch (Exception e) {
        txtcode.setText("It1001");
        System.out.println("Auto Code Error: " + e.getMessage());
    }
    
}
 
public String barcode() {
    long randomNumber = (long) (Math.random() * 900000000000L) + 100000000000L;
    return String.valueOf(randomNumber);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JComboBox<String> cmbcategory;
    private javax.swing.JTextField costprice;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItems;
    private javax.swing.JTextField txtcode;
    private javax.swing.JLabel txtcostprice;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtqty;
    // End of variables declaration//GEN-END:variables
}
