/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventorymanagementsystem;

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setSize(720, 400);             
    this.setResizable(false);             
    this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 7));
        jPanel1.setForeground(new java.awt.Color(0, 204, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Login System ");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User name");

        txt_username.addActionListener(this::txt_usernameActionPerformed);

        txt_password.addActionListener(this::txt_passwordActionPerformed);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("password");

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png"))); // NOI18N
        jButton1.setText("Login ");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 370, 370));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/20944201.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                        
String username = txt_username.getText().trim();
        String password = new String(txt_password.getPassword()).trim();

        if(username.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter Username and Password!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        final String[] userRole = {""}; 
        boolean loginSuccess = false;

        try {
            java.sql.Connection con = db.mycon();
            String sql = "SELECT role FROM users WHERE username=? AND password=?";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, password);
            
            java.sql.ResultSet rs = pst.executeQuery();
            
            if(rs.next()) {
                loginSuccess = true;
                userRole[0] = rs.getString("role");
            }
            
        } catch (java.sql.SQLException e) {
            System.out.println("Login DB Error: " + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (loginSuccess) { 
            jButton1.setEnabled(false);
            txt_username.setEnabled(false);
            txt_password.setEnabled(false);
            
            javax.swing.JPanel loadingPanel = new javax.swing.JPanel();
            loadingPanel.setBackground(new java.awt.Color(255, 255, 255)); 
            loadingPanel.setLayout(null); 
            loadingPanel.setBounds(0, 0, this.getWidth(), this.getHeight());
            
            javax.swing.JLabel loginText = new javax.swing.JLabel("Please Wait Login...", javax.swing.SwingConstants.CENTER);
            loginText.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 36)); 
            loginText.setForeground(new java.awt.Color(0, 102, 204)); 
            loginText.setBounds(0, (this.getHeight() / 2) - 60, this.getWidth(), 50); 
            loadingPanel.add(loginText);
            
            javax.swing.JProgressBar lineProgress = new javax.swing.JProgressBar(0, 100);
            lineProgress.setUI(new javax.swing.plaf.basic.BasicProgressBarUI()); 
            lineProgress.setValue(0); 
            lineProgress.setStringPainted(false); 
            lineProgress.setBorderPainted(false);
            lineProgress.setForeground(new java.awt.Color(0, 102, 204)); 
            lineProgress.setBackground(new java.awt.Color(237, 19, 19)); 
            lineProgress.setBounds((this.getWidth() / 2) - 150, (this.getHeight() / 2) + 10, 300, 6); 
            loadingPanel.add(lineProgress);
            
            this.getLayeredPane().add(loadingPanel, javax.swing.JLayeredPane.MODAL_LAYER);
            this.revalidate();
            this.repaint();
            
            javax.swing.Timer animTimer = new javax.swing.Timer(20, new java.awt.event.ActionListener() {
                int progressValue = 0;

                @Override
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    if (progressValue < 100) {
                        progressValue += 1; 
                        lineProgress.setValue(progressValue);
                    } else {
                        ((javax.swing.Timer)e.getSource()).stop();
                        
                        String finalRole = userRole[0].trim();
                        
                        if (finalRole.equalsIgnoreCase("user") || finalRole.equalsIgnoreCase("Billing") || finalRole.equalsIgnoreCase("Cashier")) {
                            
                           
                            Billing billingPage = new Billing(); 
                            billingPage.setLocationRelativeTo(null);
                            billingPage.setVisible(true);
                            
                        } else if (finalRole.equalsIgnoreCase("Admin")) {
                            
                            main dashboard = new main(finalRole); 
                            dashboard.setLocationRelativeTo(null);
                            dashboard.setVisible(true);  
                        }
                        
                        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(jButton1);
                        if (win != null) {
                            win.dispose();
                        }
                    }
                }
            });
            
            animTimer.start();

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid Username or Password!", "Login Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            txt_username.setText("");
            txt_password.setText("");
        }
    

     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
