/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.inventorymanagementsystem;

/**
 *
 * @author Admin
 */
public class setting extends javax.swing.JPanel {

    /**
     * Creates new form setting
     */
    public setting() {
        initComponents();
          try {
        tb_load();
    } catch (Exception e) {
        System.out.println(e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        deleted = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("User mange");

        jLabel2.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel2.setText("Settings");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "user name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);

        deleted.setBackground(new java.awt.Color(255, 0, 0));
        deleted.setForeground(new java.awt.Color(255, 255, 255));
        deleted.setText("Delete");
        deleted.addActionListener(this::deletedActionPerformed);

        Add.setBackground(new java.awt.Color(51, 153, 0));
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add");
        Add.addActionListener(this::AddActionPerformed);

        update.setBackground(new java.awt.Color(255, 102, 0));
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(this::updateActionPerformed);

        jLabel3.setBackground(new java.awt.Color(0, 255, 51));
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Deneth Software's");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update)
                        .addGap(18, 18, 18)
                        .addComponent(deleted))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update)
                    .addComponent(Add)
                    .addComponent(deleted))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
                                   
  
    javax.swing.JDialog d = new javax.swing.JDialog((javax.swing.JFrame)null, "Add New User", true);
    d.setSize(350, 300);
    d.setLayout(null);
    d.setLocationRelativeTo(this); 
    d.getContentPane().setBackground(new java.awt.Color(245, 245, 245)); 

    
    javax.swing.JLabel lblUser = new javax.swing.JLabel("Username:");
    lblUser.setBounds(30, 30, 100, 25);
    d.add(lblUser);

    javax.swing.JTextField txtUser = new javax.swing.JTextField();
    txtUser.setBounds(130, 30, 160, 25);
    d.add(txtUser);

    javax.swing.JLabel lblPass = new javax.swing.JLabel("Password:");
    lblPass.setBounds(30, 80, 100, 25);
    d.add(lblPass);

    javax.swing.JPasswordField txtPass = new javax.swing.JPasswordField();
    txtPass.setBounds(130, 80, 160, 25);
    d.add(txtPass);

    javax.swing.JLabel lblRole = new javax.swing.JLabel("Role:");
    lblRole.setBounds(30, 130, 100, 25);
    d.add(lblRole);

    String[] roles = {"Admin", "User"};
    javax.swing.JComboBox<String> cmbRole = new javax.swing.JComboBox<>(roles);
    cmbRole.setBounds(130, 130, 160, 25);
    d.add(cmbRole);

 
    javax.swing.JButton btnSave = new javax.swing.JButton("Save User");
    btnSave.setBounds(130, 190, 100, 30);
    btnSave.setBackground(new java.awt.Color(0, 153, 76)); 
    btnSave.setForeground(java.awt.Color.WHITE);
    d.add(btnSave);

    
    btnSave.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            String username = txtUser.getText().trim();
            String password = new String(txtPass.getPassword()).trim();
            String role = cmbRole.getSelectedItem().toString();

            if (username.isEmpty() || password.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(d, "Please fill all fields!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                java.sql.Connection con = db.mycon();
                
                
                String sql = "INSERT INTO users (username, password, role) VALUES (?, ?, ?)";
                java.sql.PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, username);
                pst.setString(2, password);
                pst.setString(3, role);

                pst.executeUpdate();

                javax.swing.JOptionPane.showMessageDialog(d, "User Registered Successfully!");
                d.dispose(); 
                
              
                tb_load(); 

            } catch (java.sql.SQLException ex) {
                System.out.println("Error: " + ex.getMessage());
                javax.swing.JOptionPane.showMessageDialog(d, "Database Error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    });

    d.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void deletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedActionPerformed
     int selectedRow = jTable1.getSelectedRow();
        
        
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a user from the table to delete!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
      
        String usernameToDelete = jTable1.getValueAt(selectedRow, 0).toString();
        
       
        int dialogResult = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete user '" + usernameToDelete + "'?", "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);
        
        if(dialogResult == javax.swing.JOptionPane.YES_OPTION){
            try {
                java.sql.Connection con = db.mycon();
                
                
                String sql = "DELETE FROM users WHERE username = ?";
                java.sql.PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, usernameToDelete);
                
                pst.executeUpdate();
                
                javax.swing.JOptionPane.showMessageDialog(this, "User Deleted Successfully!");
                
                
                tb_load(); 
                
            } catch (java.sql.SQLException ex) {
                System.out.println("Error: " + ex.getMessage());
                javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deletedActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
          








        int selectedRow = jTable1.getSelectedRow();
        
        // යම් හෙයකින් රෝ එකක් සිලෙක්ට් කරලා නැත්නම් Warning එකක් දෙනවා
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a user from the table to update!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // සිලෙක්ට් කරපු පේළියේ දැනට තියෙන Username එක ගන්නවා (මේක තමයි ඩේටාබේස් එකේ query එකට දාන්නේ)
        String currentUsername = jTable1.getValueAt(selectedRow, 0).toString();
        String currentRole = jTable1.getValueAt(selectedRow, 1).toString();

        // Popup JDialog එකක් සාදනවා
        javax.swing.JDialog d = new javax.swing.JDialog((javax.swing.JFrame)null, "Update User: " + currentUsername, true);
        d.setSize(350, 300);
        d.setLayout(null);
        d.setLocationRelativeTo(this);
        d.getContentPane().setBackground(new java.awt.Color(245, 245, 245));

        // 📝 UI Components (Username එක වෙනස් කරන්න දෙන්නේ නැහැ, Password සහ Role විතරයි)
        javax.swing.JLabel lblUser = new javax.swing.JLabel("Username:");
        lblUser.setBounds(30, 30, 100, 25);
        d.add(lblUser);

        javax.swing.JTextField txtUser = new javax.swing.JTextField(currentUsername);
        txtUser.setBounds(130, 30, 160, 25);
        txtUser.setEditable(false); // Username එක Edit කරන්න බැරි වෙන්න Lock කරනවා
        d.add(txtUser);

        javax.swing.JLabel lblPass = new javax.swing.JLabel("New Password:");
        lblPass.setBounds(30, 80, 100, 25);
        d.add(lblPass);

        javax.swing.JPasswordField txtPass = new javax.swing.JPasswordField();
        txtPass.setBounds(130, 80, 160, 25);
        d.add(txtPass);

        javax.swing.JLabel lblRole = new javax.swing.JLabel("Role:");
        lblRole.setBounds(30, 130, 100, 25);
        d.add(lblRole);

        String[] roles = {"Admin", "User"};
        javax.swing.JComboBox<String> cmbRole = new javax.swing.JComboBox<>(roles);
        cmbRole.setSelectedItem(currentRole); // දැනට තියෙන Role එක ඔටෝ සිලෙක්ට් කරනවා
        cmbRole.setBounds(130, 130, 160, 25);
        d.add(cmbRole);

        javax.swing.JButton btnUpdateSave = new javax.swing.JButton("Update");
        btnUpdateSave.setBounds(130, 190, 100, 30);
        btnUpdateSave.setBackground(new java.awt.Color(0, 102, 204)); // නිල් පාට
        btnUpdateSave.setForeground(java.awt.Color.WHITE);
        d.add(btnUpdateSave);

        // Update Event එක
        btnUpdateSave.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                String newPassword = new String(txtPass.getPassword()).trim();
                String newRole = cmbRole.getSelectedItem().toString();

                if (newPassword.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(d, "Please enter a new password!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }

                try {
                    java.sql.Connection con = db.mycon();
                    // Username එකට ගැලපෙන Password සහ Role එක අප්ඩේට් කරන SQL එක
                    String sql = "UPDATE users SET password = ?, role = ? WHERE username = ?";
                    java.sql.PreparedStatement pst = con.prepareStatement(sql);
                    pst.setString(1, newPassword);
                    pst.setString(2, newRole);
                    pst.setString(3, currentUsername);

                    pst.executeUpdate();

                    javax.swing.JOptionPane.showMessageDialog(d, "User Updated Successfully!");
                    d.dispose();
                    tb_load(); // ටේබල් එක Refresh කරනවා

                } catch (java.sql.SQLException ex) {
                    System.out.println("Error: " + ex.getMessage());
                    javax.swing.JOptionPane.showMessageDialog(d, "Database Error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        d.setVisible(true);
                               // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    public void tb_load() {
    try {
        // 1. ඩේටාබේස් කනෙක්ෂන් එක ගන්නවා
        java.sql.Connection con = db.mycon();
        java.sql.Statement s = con.createStatement();
        
        // 2. යූසර්ස්ලාගේ Username සහ Role විතරක් ටේබල් එකට ගන්න Query එක
        java.sql.ResultSet rs = s.executeQuery("SELECT username, role FROM users");
        
        // 3. JTable එකේ Model එක ලබාගෙන එහි දැනට තියෙන පේළි (Rows) හිස් කරනවා
        javax.swing.table.DefaultTableModel dt = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        dt.setRowCount(0);
        
        // 4. ResultSet එක හරහා loop වෙමින් table එකට rows එකතු කරනවා
        while (rs.next()) {
            java.util.Vector<String> v = new java.util.Vector<>();
            v.add(rs.getString("username")); // පළමු Column එක (user name)
            v.add(rs.getString("role"));     // දෙවන Column එක (Role)
            
            dt.addRow(v); // Row එක Table එකට දානවා
        }
        
    } catch (java.sql.SQLException e) {
        System.out.println("Table Load Error: " + e.getMessage());
        javax.swing.JOptionPane.showMessageDialog(this, "Table Load Error: " + e.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton deleted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
