/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.inventorymanagementsystem;

/**
 *
 * @author Zentox
 */
public class Supplier extends javax.swing.JPanel {

    /**
     * Creates new form Supplier
     */
    public Supplier() {
        initComponents();
        
        tb_load();
        auto_id();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtcompanyname = new javax.swing.JTextField();
        txtphonenumber = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 153));
        setPreferredSize(new java.awt.Dimension(1200, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel1.setText("Supplier Management ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Supplier Add/Update/Delete", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Yu Gothic", 1, 18), new java.awt.Color(255, 51, 51))); // NOI18N

        jLabel2.setText("Supplier ID:");

        jLabel3.setText("Company Name");

        jLabel4.setText("Email Address");

        jLabel5.setText("Phone number");

        txtid.addActionListener(this::txtidActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(0, 156, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtcompanyname))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtemail))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtphonenumber)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtid))))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcompanyname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 300, 300));

        jTable1.setBackground(new java.awt.Color(102, 255, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Supplier ID", "Company Name", "Phone", "Email"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(0, 51, 204));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 640, 450));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile (1).png"))); // NOI18N
        jLabel6.setText("jLabel6");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 99, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setForeground(new java.awt.Color(51, 255, 51));

        btnadd.setBackground(new java.awt.Color(102, 255, 0));
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        btnadd.setText("Add supplier");
        btnadd.addActionListener(this::btnaddActionPerformed);

        btndelete.setBackground(new java.awt.Color(255, 51, 51));
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user (1).png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(this::btndeleteActionPerformed);

        btnclear.setBackground(new java.awt.Color(255, 255, 102));
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/broom.png"))); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(this::btnclearActionPerformed);

        btnupdate.setBackground(new java.awt.Color(255, 153, 51));
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updated.png"))); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(this::btnupdateActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnadd)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 310, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
         String id = txtid.getText();
        String name = txtcompanyname.getText();
        String phone = txtphonenumber.getText();
        String email = txtemail.getText();
        
        if(id.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a Supplier from Table to update!");
            return;
        }
        if(name.isEmpty() || phone.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Company Name and Phone cannot be empty!");
            return;
        }

        try {
            java.sql.Connection con = db.mycon();
            java.sql.PreparedStatement pst = con.prepareStatement(
                "UPDATE suppliers SET company_name=?, phone=?, email=? WHERE supplier_id=?"
            );
            pst.setString(1, name);
            pst.setString(2, phone);
            pst.setString(3, email);
            pst.setString(4, id); 
            
            int rows = pst.executeUpdate();
            if(rows > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Supplier Updated Successfully!");
                tb_load();                     
                btnclearActionPerformed(null); 
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Supplier ID not found!");
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
   auto_id(); 
        String id = txtid.getText(); 
        String name = txtcompanyname.getText();
        String phone = txtphonenumber.getText().trim();
        String email = txtemail.getText().trim();
      if (!phone.matches("\\d{10}")) {
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Please enter a valid phone number! (Must be exactly 10 digits)", 
        "Validation Error", 
        javax.swing.JOptionPane.WARNING_MESSAGE);
    txtphonenumber.requestFocus();
    return; 
}

if (!phone.matches("\\d{10}")) {
    javax.swing.JOptionPane.showMessageDialog(null, 
        "Please enter a valid phone number! (Must be exactly 10 digits)", 
        "Validation Error", 
        javax.swing.JOptionPane.WARNING_MESSAGE);
    txtphonenumber.requestFocus();
    return; 
}

// 2. Email Validation (@ අකුර තියෙනවාද බලනවා)
if (!email.contains("@")) {
    javax.swing.JOptionPane.showMessageDialog(null, 
        "Please enter a valid Email address! (@ symbol is required)", 
        "Validation Error", 
        javax.swing.JOptionPane.WARNING_MESSAGE);
    txtemail.requestFocus();
    return; 
}
    
 {
  
        try {
            java.sql.Connection con = db.mycon();
            java.sql.PreparedStatement pst = con.prepareStatement(
                "INSERT INTO suppliers (supplier_id, company_name, phone, email) VALUES (?,?,?,?)"
            );
            pst.setString(1, id); 
            pst.setString(2, name);
            pst.setString(3, phone);
            pst.setString(4, email);
            
            pst.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Supplier Added Successfully!");
            
            tb_load(); 
            btnclearActionPerformed(null); 
            
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }                          
 
}
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
                         
          txtid.setText("");
        txtcompanyname.setText("");
        txtphonenumber.setText("");
        txtemail.setText("");
        auto_id();
      
    }//GEN-LAST:event_btnclearActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
     String id = txtid.getText();
    
    // Validation: ID එකක් තියෙන්නම ඕනේ delete කරන්න
    if(!id.isEmpty()){
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select or enter a Supplier ID to delete!");
        return;
    }
    
    // User ගෙන් ඇත්තටම මකන්න ඕනෙද කියලා අහන Confirmation බොක්ස් එකක්
    int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to delete this supplier (" + id + ")?", 
        "Delete Confirmation", 
        javax.swing.JOptionPane.YES_NO_OPTION
    );
    
    // User "YES" ක්ලික් කරොත් විතරක් delete කරනවා
    if(confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            java.sql.Connection con = db.mycon();
            // SQL Delete Query එක
            java.sql.PreparedStatement pst = con.prepareStatement("DELETE FROM suppliers WHERE supplier_id=?");
            pst.setString(1, id);
            
            int rows = pst.executeUpdate();
            
            if(rows > 0){
                javax.swing.JOptionPane.showMessageDialog(this, "Supplier Deleted Successfully!");
                tb_load();                     // Table එක refresh කරනවා
                btnclearActionPerformed(null); // Fields ටික clear කරලා අලුත් ID එකක් දානවා
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Supplier ID not found!");
            }
            
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        
        }}
            // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
                                              
    int r = jTable1.getSelectedRow();
    
    // Table එකෙන් දත්ත ටික ගන්නවා
    String id = jTable1.getValueAt(r, 0).toString();
    String name = jTable1.getValueAt(r, 1).toString();
    String phone = jTable1.getValueAt(r, 2).toString();
    String email = jTable1.getValueAt(r, 3) != null ? jTable1.getValueAt(r, 3).toString() : "";
    
    // Text fields වලට දත්ත ටික සෙට් කරනවා
    txtid.setText(id);
    txtcompanyname.setText(name);
    txtphonenumber.setText(phone);
    txtemail.setText(email);
      // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    public void auto_id() {
    try {
        // db class එක හරහා database එකට connect වීම
        java.sql.Connection con = db.mycon(); 
        java.sql.Statement s = con.createStatement();
        
        // suppliers table එකේ දැනට තියෙන ලොකුම ID එක query කරලා ගන්නවා
        java.sql.ResultSet rs = s.executeQuery("SELECT MAX(supplier_id) FROM suppliers");
        
        if (rs.next() && rs.getString(1) != null) {
            String maxId = rs.getString(1); // උදාහරණයක් ලෙස: "S1001"
            
            // "S" අකුර අතහැර ඉතිරි අංක කොටස (1001) පමණක් වෙන් කර ගැනීම
            int idNum = Integer.parseInt(maxId.substring(1)); 
            idNum++; // අංකය 1කින් වැඩි කිරීම (1001 -> 1002)
            
            // නැවතත් "S" අකුර සමඟ අලුත් අංකය එකතු කර text field එකට දැමීම
            txtid.setText("S" + idNum);
        } else {
            // Database එකේ කිසිම කෙනෙක් නැත්නම් මුල්ම ID එක ලෙස S1001 ලබා දීම
            txtid.setText("S1001");
        }
        
        // User ට මේ ID එක manually වෙනස් කරන්න බැරි වෙන්න lock කිරීම (UI Best Practice)
        txtid.setEditable(false); 
        
    } catch (java.sql.SQLException e) {
        System.out.println("Auto ID Error: " + e.getMessage());
    }
}
    public void tb_load() {
    try {
        java.sql.Connection con = db.mycon();
        java.sql.Statement s = con.createStatement();
        java.sql.ResultSet rs = s.executeQuery("SELECT * FROM suppliers");
        
        // Table model එක ලබා ගැනීම
        javax.swing.table.DefaultTableModel dt = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        dt.setRowCount(0); // කලින් තිබුන row අයින් කිරීම
        
        while (rs.next()) {
            java.util.Vector v = new java.util.Vector();
            v.add(rs.getString("supplier_id"));
            v.add(rs.getString("company_name"));
            v.add(rs.getString("phone"));
            v.add(rs.getString("email"));
            
            dt.addRow(v);
        }
    } catch (java.sql.SQLException e) {
        System.out.println(e.getMessage());
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcompanyname;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtphonenumber;
    // End of variables declaration//GEN-END:variables
}
